# Generated by Django 3.2.10 on 2022-01-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='date',
            new_name='blog_date',
        ),
    ]
